project_name: clockwerk
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io,direct
before:
  hooks:
    # - go mod download
    - make generate
    - make format
    # - make lint
    # - make test
builds:
  - id: "clockwerk"
    binary: clockwerk
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    flags:
      - -v
      # go1.13
      - -trimpath
    asmflags:
      # use go build -trimpath instead for go1.13
      # - all=-trimpath={{.Env.PWD}}
    gcflags:
      # use go build -trimpath instead for go1.13
      # - all=-trimpath={{.Env.PWD}}
    ldflags:
      - >-
        -s -w
        -X main.ProductVersion={{.Version}}
        -X main.GitCommit={{.ShortCommit}}
        -X main.GoVersion={{.Env.GOVERSION}}
        -X main.BuildTime={{.Date}}
  
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - clockwerk
    extra_files:
      - config.yaml
    image_templates:
      - "zhaojj11/clockwerk:latest"
      - "zhaojj11/clockwerk:{{ .Tag }}"
      - "zhaojj11/clockwerk:v{{ .Major }}.{{ .Minor }}"
    dockerfile: Dockerfile

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
