name: "clockwerk"
mode: "dev"
port: 8000
version: "v0.0.1"

log:
  level: "debug"
  filename: "./log/clockwerk.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "clockwerk"
  max_open_conns: 200
  max_idle_conns: 50