name: "clockwerk"
mode: "dev"
port: 8000
version: "v0.0.1"

secret:
  param: 123456

log:
  level: "debug"
  filename: "./logger/clockwerk.logger"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123"
  dbname: "clockwerk"
