name: "clockwerk"
port: 8080
mode: dev
version: 0.0.1

log:
  level: "debug"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "zjj12345"
  dbname: "clockwerk"

redis:
  host: "127.0.0.1"
  port: 6379

jwt:
  key: "EYsnfKMf5XWk87LASEs28Dj5ZqGkSerH"